title: "aletss's Blog"
description: "Blog personal para escribir lo que no debe ser le√≠do (por aburrido)."
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-remote-theme

exclude:
  - about.html
  - contact.html

email: "551sosamurguia@gmail.com"